version: '3.8'

services:
    api:
        container_name: colendi-case
        build:
            context: .
            target: ${APP_MODE}
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - c-network
        volumes:
            - ./:/app
            - /app/node_modules
        restart: always
        depends_on:
            - postgres-db

    postgres-db:
      container_name: postgres-db
      image: postgres:15.3-alpine3.18
      restart: unless-stopped
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      env_file:
        - .env
      volumes:
        - postgres:/var/lib/postgresql/data
      networks:
        - c-network

volumes:
   postgres:
      name: postgres-db

networks:
    c-network: